version: '3'
services:
  web:
    image: level3/python
    ports:
      - "8088:5000"
    volumes:
      - .:/code
  redis:
    image: "redis:alpine"
    command: "redis-server --appendonly yes"
    volumes:
      - redis_store:/data

volumes:
  redis_store:
