version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
  redis:
    image: "redis:alpine"
    command: "redis-server --appendonly yes"
    volumes:
      - redis_store:/data

volumes:
  redis_store:

