version: '3'
services:
  go-api:
    image: go-redis
    environment:
      - REDIS_HOST=redis:6379
    ports:
      - "3000:3000"

  redis:
    image: "redis:alpine"
    command: "redis-server --appendonly yes"
    volumes:
      - redis_store:/data

volumes:
  redis_store:
